---
title: "March Madness Project Vignette"
author: "AJ Haygood, Dylan Perrenoud, Jonah Feigleson"
date: "`r Sys.Date()`"
output: pdf_document
vignette: >
  %\VignetteIndexEntry{March Madness Project Vignette}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

# Github URL

https://github.com/djperrenoud/march.madness

# Introduction

This vignette describes how to use the `march.madness` package. This package provides tools for predicting outcomes of NCAA March Madness basketball games based on historical and current season data.

# Installation

You can install the released version of `march.madness` from CRAN with:

``` r
install.packages("march.madness")
```

# Data Cleaning

This section outlines the data cleaning procedures implemented in the 'clean_data.R' script, which are designed to refine the data set in alignment with the project's objectives. The process involves removing columns that are not essential for the analysis. Specifically, non-essential data such as conference identifiers, team IDs, and ranking values of various metrics are excluded. For example, while the Kenpom adjusted offensive value is retained, its corresponding ranking values are discarded. This approach enables the direct utilization of actual metric values for more effective comparisons and predictions, rather than relying on their ranked positions.

# Main Functions

## Selection Functions

### Team Name Formatting

#### `format_team_name(team)`

The `format_team_name` function is designed to correct and standardize team names input by users, ensuring consistency with the naming conventions used in the dataset. It manages variations and common typographical errors, and it adjusts specific formatting for known team names based on predefined rules.

-   **Details**:

    -   Takes user input an lower cases every letter from the start

    -   First checks if the input is part of the "special cases" to insure correct capitalization:

        -   Loyola MD
        -   LIU Brooklyn
        -   UT Arlington
        -   UNC Asheville
        -   McNeese St.
        -   UC Davis
        -   UC Irvine
        -   UC Santa Barbara

    -   Checks if the input is apart of the "saint cases" to output "Saint" correctly:

        -   Mount St. Mary's is the exception
        -   Saint Louis
        -   Saint Joseph's
        -   Saint Mary's
        -   Saint Peter's

    -   Checks if the school is an A&M or A&T school:

        -   North Carolina A&T
        -   Praire View A&M
        -   Texas A&M
        -   Texas A&M Corpus Christi

    -   Checks if the input is apart of the 4 letter all caps cases:

        -   UNLV
        -   UTEP
        -   UTSA
        -   UMBC

    -   Checks if the input is the "Miami case"

        -   Since there are two universities named "Miami", if a user inputs "Miami" it automatically will switch the input to "Miami FL" due to the fact that Miami Ohio is not included in the dataset. The user will receive a warning letting them know that "Miami" was coerced to "Miami FL".

    -   Checks if the input is apart of the 3 letter all caps cases

    -   After checking these cases, general capitalization rules will apply, capitalizing the first letter in each word

    -   The function also allows for the user to input "St." as "state" or "st" to allow some error from the user.

-   **Parameters**:

    -   `team`: A character string representing the team name as inputted by the user.

-   **Returns**:

    -   A character string with the properly formatted team name to match the dataset's expected format.

-   **Example**:

``` r
# Example of handling a common abbreviation
formatted_team <- format_team_name("utah st")
print(formatted_team) # Outputs "Utah St."

# Handling a university name with special abbreviations
formatted_team <- format_team_name("uc irvine")
print(formatted_team) # Outputs "UC Irvine"

# Correcting and standardizing 'Saint' school names
formatted_team <- format_team_name("st joseph's")
print(formatted_team) # Outputs "Saint Joseph's"
```

### Team Selection

#### `team_select(team, year)`

This function creates a custom S3 object for a specific team and year, effectively sub-setting the main data set to focus on data relevant to the specified parameters. The function takes a team name and a year as inputs and returns a subset of data as a custom S3 object of class 'teamdata'.

-   **Parameters**:

    -   `team`: A character string representing the team name.
    -   `year`: An integer representing the year.

-   **Returns**:

    -   A custom S3 object of class 'teamdata' containing the subsetted data.

-   **Example**:

``` r
selected_team <- team_select("Baylor", 2024)
print(selected_team)
```

### Match-up Selection

#### `matchup_select(team1, year1, team2, year2)`

This function facilitates the creation of a custom S3 object representing the data for two specific teams and their respective years, designed for matchup analysis. It processes inputs for two teams and their corresponding years, and returns a detailed comparison setup in a structured format.

-   **Parameters**:

    -   `team1`: A character string representing the name of the first team.
    -   `year1`: An integer representing the competition year of the first team.
    -   `team2`: A character string representing the name of the second team.
    -   `year2`: An integer representing the competition year of the second team.

-   **Returns**: A custom S3 object of class 'teamdata_matchup' which contains a list of the subsetted data for each team and year.

-   **Example**:

``` r
selected_matchup <- matchup_select("Baylor", 2023, "Purdue", 2023)
print(selected_matchup)
```

## Visualization Functions

### Team Table

#### `team_table(selected_team)`

This function creates a simple table showing basic information about the team. This includes team name, year, conference, seed, the round they made it to, wins and losses.

-   **Parameters**:

    -   `selected_team`: A custom S3 object of class 'teamdata' containing subsetted data for the specified team.

-   **Returns**: A data table with team name, year, conference, seed, round, wins and losses for the specified team.

-   **Example**:

``` r
team_table(team_select("Baylor", 2024))
```

### Stat Table

#### `stat_table(selected_team)`

This function creates a simple table showing important success indicators for a team. These include efficiency field goals, free throw rate, offensive rebounds, and turnover rate.

-   **Parameters**:

    -   `selected_team`: A custom S3 object of class 'teamdata' containing subsetted data for the specified team.

-   **Returns**: A data table with the statistics specified in the description.

-   **Example**:

``` r
stat_table(team_select("Baylor", 2024))
```

### Match up Visualization

#### `matchup_chart(teamdata_matchup)`

This function takes two teams and compares four important statistics (Efficiency Field Goals, Free Throw Rate, Offensive Rebounds, and Turnover Rate) to give insights on which team is better. The output of the function is a bar chart showing side by side percentages for each team's metrics.

-   **Parameters**:

    \-`teamdata_matchup`: A custom S3 object of class 'teamdata_matchup' which contains a list of the subsetted data for each team and year.

-   **Returns**: A side-by-side bar chart showing a comparison of the four important statistics described above.

-   **Example**:

``` r
matchup_table(matchup_select("Baylor", 2024, "Purdue", 2024))
```

## Match up Function

#### `matchup_prob(teamdata_matchup)`

Gives two selected teams a "power" rating based on their statistics and uses this and a normal distribution to simulate the probability of each team winning.

-   **Parameters**:

    -   `teamdata_matchup`

-   **Returns**:

    -   Power Index's for teams 1 and 2
    -   Probability of winning for teams 1 and 2
    -   Final prediction based off of weighted coinflip

-   **Example**:

``` r
teamdata_matchup <- matchup_select("Purdue", 2024, "Utah St.", 2024)
matchup_prob(teamdata_matchup)
```
